#! /usr/bin/env ruby

libs = []
libs << "irb/completion"
libs << File.dirname(__FILE__) + '/../environment.rb'

command_line = []
command_line << "irb"
command_line << libs.inject("") { |acc, lib| acc + %( -r "#{lib}") }
command_line << "--simple-prompt"
command = command_line.join(" ")

Readline.try(:vi_editing_mode) rescue nil

puts "Welcome to the sinatra console in #{ENV['RACK_ENV'] || 'development'}"
exec command
